### ISSUE TITLE
Excel Export Formatting Request

### ISSUE THREAD

**Issue by jjc6676** [Sewersidesquad/MintTracker#1]
How could I change the information captured per excel cell?

For me specifically, I would like to have columns with one item per cell for filtering and growing downward in cells vs putting the data in one cell.

Is this possible?

Ideally for me it would be in order

Collection (NAME)
Sub Collection (Description)
List Of Owner Account ID(s)
List Of Owner Wallet Address(es)
Royalty Percentage
Quantity
Ipfs MetaData CID
Image CID

This is something that would allow me to filter down easier

**Comment by Sewersidesquad** [comment]
I'm not 100% sure what you mean by this. I'll have a look think but I'm not super familiar with spreadsheets so I'm struggling to picture exactly what you mean. Thanks for the suggestion though!

**Comment by jjc6676** [comment]
I could give you a screenshot.
Look here https://i.imgur.com/qPk8Grm.png

Obviously I omitted a few lines like account id's but this should give you a better idea.

**Comment by Sewersidesquad** [comment]
Hmm, that does help thankyou, for now, I'll make a separate app for that. I'll reply back with it here. It's mostly the same as this one so won't take long as it would to add as a feature. So just to be clear for each nft there would be one piece of data for each, as in one address from the list and then you could have the same nft multiple times but with different holders on each line?

**Comment by Sewersidesquad** [comment]
Actually, because I'm going to update this app in the next couple of hours with the quantity and some other little features it might be easier to leave it as the messier spreadsheet. But I'll get started tomorrow on a much cleaner spreadsheet because the spreadsheet isn't great. I'll have it so it'll work in the way that you mentioned as default, I hadn't used the spreadsheet really at all and just checked to make sure it was working correctly but after looking at it properly, it's a mess. Thanks for pointing me in the right direction with the suggestion!

**Comment by Sewersidesquad** [comment]
Should be much better now. Hope it's useful! - https://github.com/Sewersidesquad/MintTracker/releases/tag/v1.1.1

**Comment by jjc6676** [comment]
Much appreciation - I will test it now and report back if I find any new issues by opening a new issue!
